feat: added app remove/destroy code to cicd process (#7)

diff --git a/.github/workflows/manual-deploy-or-destroy-prod.yaml b/.github/workflows/manual-deploy-or-destroy-prod.yaml
--- a/.github/workflows/manual-deploy-or-destroy-prod.yaml
+++ b/.github/workflows/manual-deploy-or-destroy-prod.yaml
@@ -107,12 +107,12 @@ jobs:
           ref: ${{ github.event.inputs.releaseRef }}
 
       - name: Query AWX for Job Template
-        id: query_job_template
+        id: query_deploy_job_template
         env:
           AWX_USER: ${{ secrets.AWX_USER }}
           AWX_PW: ${{ secrets.AWX_PW }}
           AWX_HOST: ${{ secrets.AWX_HOST }}
-          JOB_TEMPLATE_NAME: "Deploy%20-%20Cloudflare%20DDNS%20%28Containerized%29"
+          JOB_TEMPLATE_NAME: "Cloudflare%20DDNS%20%28Containerized%29%20-%20Deploy"
         run: |
           RESPONSE=$(curl -s -u "$AWX_USER:$AWX_PW" \
             -H "Content-Type: application/json" \
@@ -129,13 +129,13 @@ jobs:
           echo "job_template_id=$JOB_TEMPLATE_ID" >> $GITHUB_OUTPUT
 
       - name: Launch AWX Job Template
-        id: launch_job
+        id: launch_deploy_job
         env:
           AWX_USER: ${{ secrets.AWX_USER }}
           AWX_PW: ${{ secrets.AWX_PW }}
           AWX_HOST: ${{ secrets.AWX_HOST }}
         run: |
-          JOB_TEMPLATE_ID="${{ steps.query_job_template.outputs.job_template_id }}"
+          JOB_TEMPLATE_ID="${{ steps.query_deploy_job_template.outputs.job_template_id }}"
           LAUNCH_RESPONSE=$(curl -L -s -u "$AWX_USER:$AWX_PW" \
             -H "Content-Type: application/json" \
             -X POST \
@@ -156,7 +156,7 @@ jobs:
           AWX_PW: ${{ secrets.AWX_PW }}
           AWX_HOST: ${{ secrets.AWX_HOST }}
         run: |
-          JOB_ID="${{ steps.launch_job.outputs.job_id }}"
+          JOB_ID="${{ steps.launch_deploy_job.outputs.job_id }}"
           echo "Polling AWX for status of Job ID: $JOB_ID"
           STATUS=""
           # Poll every 10 seconds, up to a maximum of 30 minutes (180 iterations)
@@ -180,9 +180,131 @@ jobs:
             echo "Job completed successfully. Final status: $STATUS"
           fi
 
-  destroy:
+  destroy-app-cleanup:
     runs-on: github-arc-runners
     if: ${{ github.event.inputs.actionSelection == 'Destroy' }}
+    permissions:
+      contents: read
+    steps:
+      - name: Checkout Repo
+        uses: actions/checkout@v4
+        with:
+          ref: ${{ github.event.inputs.releaseRef }}
+
+      - name: Query AWX for Job Template
+        id: query_remove_job_template
+        env:
+          AWX_USER: ${{ secrets.AWX_USER }}
+          AWX_PW: ${{ secrets.AWX_PW }}
+          AWX_HOST: ${{ secrets.AWX_HOST }}
+          JOB_TEMPLATE_NAME: "Cloudflare%20DDNS%20%28Containerized%29%20-%20Remove"
+        run: |
+          RESPONSE=$(curl -s -u "$AWX_USER:$AWX_PW" \
+            -H "Content-Type: application/json" \
+            "https://$AWX_HOST/api/v2/job_templates/?name=${JOB_TEMPLATE_NAME}")
+
+          JOB_TEMPLATE_ID=$(echo "$RESPONSE" | jq -r '.results[0].id')
+        
+          if [ "$JOB_TEMPLATE_ID" = "null" ] || [ -z "$JOB_TEMPLATE_ID" ]; then
+            echo "Error: No job template found with name ${JOB_TEMPLATE_NAME}" >&2
+            exit 1
+          fi
+
+          echo "Found job template ID: $JOB_TEMPLATE_ID"
+          echo "job_template_id=$JOB_TEMPLATE_ID" >> $GITHUB_OUTPUT
+
+      - name: Launch AWX Job Template
+        id: launch_remove_job
+        env:
+          AWX_USER: ${{ secrets.AWX_USER }}
+          AWX_PW: ${{ secrets.AWX_PW }}
+          AWX_HOST: ${{ secrets.AWX_HOST }}
+        run: |
+          JOB_TEMPLATE_ID="${{ steps.query_remove_job_template.outputs.job_template_id }}"
+          LAUNCH_RESPONSE=$(curl -L -s -u "$AWX_USER:$AWX_PW" \
+            -H "Content-Type: application/json" \
+            -X POST \
+            -d '{}' \
+            "https://$AWX_HOST/api/v2/job_templates/${JOB_TEMPLATE_ID}/launch/")
+
+          JOB_ID=$(echo "$LAUNCH_RESPONSE" | jq -r '.job')
+          if [ "$JOB_ID" = "null" ] || [ -z "$JOB_ID" ]; then
+            echo "Error: No job ID returned in launch response." >&2
+            exit 1
+          fi
+          echo "Launched Job ID: $JOB_ID"
+          echo "job_id=$JOB_ID" >> $GITHUB_OUTPUT
+
+      - name: Poll for Job Status
+        env:
+          AWX_USER: ${{ secrets.AWX_USER }}
+          AWX_PW: ${{ secrets.AWX_PW }}
+          AWX_HOST: ${{ secrets.AWX_HOST }}
+        run: |
+          JOB_ID="${{ steps.launch_remove_job.outputs.job_id }}"
+          echo "Polling AWX for status of Job ID: $JOB_ID"
+          STATUS=""
+          # Poll every 10 seconds, up to a maximum of 30 minutes (180 iterations)
+          for i in {1..180}; do
+            RESPONSE=$(curl -s -u "$AWX_USER:$AWX_PW" \
+              -H "Content-Type: application/json" \
+              "https://$AWX_HOST/api/v2/jobs/$JOB_ID/")
+
+            STATUS=$(echo "$RESPONSE" | jq -r '.status')
+            
+            if [[ "$STATUS" == "successful" || "$STATUS" == "failed" || "$STATUS" == "error" ]]; then
+              break
+            fi
+            sleep 10
+          done
+
+          if [ "$STATUS" != "successful" ]; then
+            echo "Job did not complete successfully. Final status: $STATUS"
+            exit 1
+          else
+            echo "Job completed successfully. Final status: $STATUS"
+          fi
+
+  destroy-awx-resources:
+    runs-on: github-arc-runners
+    needs:
+      - destroy-app-cleanup
+    permissions:
+      contents: read
+    steps:
+      - name: Checkout Repo
+        uses: actions/checkout@v4
+        with:
+          ref: ${{ github.event.inputs.releaseRef }}
+
+      - name: Install Python
+        uses: actions/setup-python@v5
+        with:
+          python-version: '3.13'
+          cache: 'pip'
+
+      - name: Install Python Dependencies
+        run: pip install -r requirements.txt
+
+      - name: Install Ansible Playbook Dependencies
+        run: ansible-galaxy collection install awx.awx
+
+      - name: Run AWX Resource Deletion Playbook
+        env:
+          CONTROLLER_HOST: ${{ secrets.AWX_HOST }}
+          CONTROLLER_USERNAME: ${{ secrets.AWX_USER }}
+          CONTROLLER_PASSWORD: ${{ secrets.AWX_PW }}
+        working-directory: ansible
+        run: |
+          ansible-playbook \
+            -i localhost \
+            -e @envs/prod.yaml \
+            delete-awx-cloudflare-ddns-deployment-resources.yaml
+
+  destroy-tf:
+    runs-on: github-arc-runners
+    needs:
+      - destroy-awx-resources
     permissions:
       contents: read
     defaults:
